### ISSUE TITLE
We need more branches, master!

### ISSUE THREAD

**Issue by volodymyr-kushnir** [foxonom/BSA#2]
Hey, @foxonom, how's it going?

Here's the deal, I got a situation recently when one of the participants made all the changes locally and then merged them locally and pushed to upstream already merged master branch, so I couldn't see the whole history because obviously GitHub didn't get it. That's my bad (I didn't see that coming, I thought that authors will push all their branches), but could you please push your branches more often?

Shout @volodymyr-kushnir if you've got questions. Thanks.

**Comment by foxonom** [comment]
Ok. I can do that. Thanks.
